# Generated by Django 5.1.5 on 2025-04-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_comment_name_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
