# Generated by Django 5.1.5 on 2025-05-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
